name: 🍎 Mac OS Build Android Debug AAB

on:
  workflow_dispatch:

jobs:
  build-android-aab:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Debug AAB
        run: yarn android:aab:debug

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-aab
          path: android/app/build/outputs/bundle/debug/app-debug.aab
          retention-days: 2
